[env]
build_unflags = -std=gnu++11
build_flags = -std=gnu++17 -Wall -Wextra -Werror=switch

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-110
test_ignore = *

[env:native]
platform = native
test_framework = unity
build_src_filter = -<*>
